add_test( array1d /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests array1d  )
set_tests_properties( array1d PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( array2d /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests array2d  )
set_tests_properties( array2d PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[World - Construction and Accessors]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[World - Construction and Accessors]==]  )
set_tests_properties( [==[World - Construction and Accessors]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[World - Conversion to heffte::box3d<int>]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[World - Conversion to heffte::box3d<int>]==]  )
set_tests_properties( [==[World - Conversion to heffte::box3d<int>]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[World - Invalid Construction]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[World - Invalid Construction]==]  )
set_tests_properties( [==[World - Invalid Construction]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Decomposition class tests]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Decomposition class tests]==]  )
set_tests_properties( [==[Decomposition class tests]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( DiscreteField1D /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests DiscreteField1D  )
set_tests_properties( DiscreteField1D PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[FieldModifier applies field modification to the model]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[FieldModifier applies field modification to the model]==]  )
set_tests_properties( [==[FieldModifier applies field modification to the model]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[FieldModifier can be used polymorphically]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[FieldModifier can be used polymorphically]==]  )
set_tests_properties( [==[FieldModifier can be used polymorphically]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[FieldModifier can be moved]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[FieldModifier can be moved]==]  )
set_tests_properties( [==[FieldModifier can be moved]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Field name can be set and retrieved]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Field name can be set and retrieved]==]  )
set_tests_properties( [==[Field name can be set and retrieved]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[FFT forward transformation]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[FFT forward transformation]==]  )
set_tests_properties( [==[FFT forward transformation]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[FFT backward transformation]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[FFT backward transformation]==]  )
set_tests_properties( [==[FFT backward transformation]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Constant Field Modifier]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Constant Field Modifier]==]  )
set_tests_properties( [==[Constant Field Modifier]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Model functionality]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Model functionality]==]  )
set_tests_properties( [==[Model functionality]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[MultiIndex Example Test]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[MultiIndex Example Test]==]  )
set_tests_properties( [==[MultiIndex Example Test]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Simulator functionality]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Simulator functionality]==]  )
set_tests_properties( [==[Simulator functionality]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Time initialization]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Time initialization]==]  )
set_tests_properties( [==[Time initialization]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Time increment]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Time increment]==]  )
set_tests_properties( [==[Time increment]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Time completion]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Time completion]==]  )
set_tests_properties( [==[Time completion]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
add_test( [==[Time save condition]==] /home/rk015/dev/buildOpenPFC/tests/OpenPFCTests [==[Time save condition]==]  )
set_tests_properties( [==[Time save condition]==] PROPERTIES WORKING_DIRECTORY /home/rk015/dev/buildOpenPFC/tests)
set( OpenPFCTests_TESTS array1d array2d [==[World - Construction and Accessors]==] [==[World - Conversion to heffte::box3d<int>]==] [==[World - Invalid Construction]==] [==[Decomposition class tests]==] DiscreteField1D [==[FieldModifier applies field modification to the model]==] [==[FieldModifier can be used polymorphically]==] [==[FieldModifier can be moved]==] [==[Field name can be set and retrieved]==] [==[FFT forward transformation]==] [==[FFT backward transformation]==] [==[Constant Field Modifier]==] [==[Model functionality]==] [==[MultiIndex Example Test]==] [==[Simulator functionality]==] [==[Time initialization]==] [==[Time increment]==] [==[Time completion]==] [==[Time save condition]==])
