
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/cmake/3.27.7/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 4.18.0-553.27.1.el8_10.x86_64 - x86_64
...
